version: '3'
services:
  api:
    container_name: ps2alerts-api
    image: ps2alerts-api:dev
    volumes:
      - ../../:/var/www/html:rw
    networks:
      - traefik
    labels:
      traefik.frontend.rule: "Host:dev.api.ps2alerts.com"
      traefik.docker.network: "traefik"
      traefik.port: "80"
      traefik.enable: "true"

networks:
  traefik:
    external: true